name: Lint Helm Chart

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Lint Chart
        run: helm lint .