name: Lint Helm Chart

on:
  push:
    branches:
      - "*"
  pull_request:
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.12.0

      - name: Lint Helm Charts
        run: helm lint .
